package db;

import model.User;
import util.DBConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object for the users table.
 * Handles all database operations related to users: find, insert, update, delete.
 *
 * All SQL queries use prepared statements to prevent SQL Injection attacks.
 */
public class UserDAO {

    /**
     * Finds a user by their username.
     * Used during login to look up the user and verify their password.
     *
     * @param username the username to search for
     * @return the User object, or null if not found
     * @throws SQLException if a database error occurs
     */
    public User findByUsername(String username) throws SQLException {
        String sql = "SELECT id, username, password_hash, role, created_at FROM users WHERE username = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, username);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return mapRow(rs);
                }
            }
        }
        return null; // user not found
    }

    /**
     * Finds a user by their ID.
     *
     * @param id the user's ID
     * @return the User object, or null if not found
     * @throws SQLException if a database error occurs
     */
    public User findById(int id) throws SQLException {
        String sql = "SELECT id, username, password_hash, role, created_at FROM users WHERE id = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, id);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return mapRow(rs);
                }
            }
        }
        return null;
    }

    /**
     * Returns a list of all users in the system.
     * Used by admins to manage users.
     *
     * @return list of all users (may be empty, never null)
     * @throws SQLException if a database error occurs
     */
    public List<User> findAll() throws SQLException {
        String sql = "SELECT id, username, password_hash, role, created_at FROM users ORDER BY id";
        List<User> users = new ArrayList<>();

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                users.add(mapRow(rs));
            }
        }
        return users;
    }

    /**
     * Inserts a new user into the database.
     * The password must already be hashed before calling this method.
     *
     * @param user the User object to insert (id is ignored, auto-generated by DB)
     * @return the auto-generated ID of the new user
     * @throws SQLException if a database error occurs (e.g. duplicate username)
     */
    public int insert(User user) throws SQLException {
        String sql = "INSERT INTO users (username, password_hash, role) VALUES (?, ?, ?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, user.getUsername());
            stmt.setString(2, user.getPasswordHash());
            stmt.setString(3, user.getRole());
            stmt.executeUpdate();

            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) {
                    return keys.getInt(1);
                }
            }
        }
        throw new SQLException("Insert failed, no ID returned.");
    }

    /**
     * Deletes a user by their ID.
     *
     * @param id the ID of the user to delete
     * @throws SQLException if a database error occurs
     */
    public void delete(int id) throws SQLException {
        String sql = "DELETE FROM users WHERE id = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, id);
            stmt.executeUpdate();
        }
    }

    /**
     * Maps a single ResultSet row to a User object.
     * Called after every query to convert DB data into a Java object.
     */
    private User mapRow(ResultSet rs) throws SQLException {
        return new User(
            rs.getInt("id"),
            rs.getString("username"),
            rs.getString("password_hash"),
            rs.getString("role"),
            rs.getString("created_at")
        );
    }
}
